pipeline {
    agent any
    tools {
        jdk 'jdk21'
    }
    environment {
        IMAGE_NAME = "krishanu123456/ad-service"   // ✅ Remove :latest from here
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'git-cred',
                    url: 'https://github.com/krishanudas0100/ultimate-devops-project-demo.git'
            }
        }
        stage('Build Ad Service') {
            steps {
                dir('src/ad') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x verifyGoogleJavaFormat'
                }
            }
        }
        stage('Trivy File Scan') {
            steps {
                sh 'trivy fs .'
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('src/ad') {
                    script {
                        withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                            sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."  // ✅ krishanu12/ad-service:9
                        }
                    }
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: 'docker-cred', toolName: 'docker') {
                        sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"            // ✅ krishanu12/ad-service:9
                        sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest"
                        sh "docker push ${IMAGE_NAME}:latest"                  // ✅ also push latest
                    }
                }
            }
        }
        stage('Deploy To Kubernetes') {
            steps {
                withKubeConfig(
                    credentialsId: 'k8-cred',
                    namespace: 'webapps'
                ) {
                    sh 'kubectl apply -f kubernetes/ad-deployment.yaml'
                }
            }
        }
    }
}
